#!/usr/bin/env python
from setuptools import setup, find_packages
import versioneer

setup(
    name='dmpipe',
    version=versioneer.get_version(),
    cmdclass=versioneer.get_cmdclass(),
    author='Matthew Wood',
    author_email='mdwood@slac.stanford.edu',
    description='Pipeline Scripts for LAT DM Analysis',
    license='BSD',
    packages=find_packages(),
    include_package_data=True,
    url="https://github.com/fermiPy/dmpipe",
    classifiers=[
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Scientific/Engineering :: Astronomy',
        'Development Status :: 4 - Beta',
    ],
    scripts=[],
    entry_points={'console_scripts': [
        'dmpipe-analyze-roi = dmpipe.target_analysis:main_roi_single',
        'dmpipe-analyze-sed = dmpipe.target_analysis:main_sed_single',
        'dmpipe-prepare-targets = dmpipe.target_analysis:main_prepare_targets',
        'dmpipe-random-dir-gen = dmpipe.target_sim:main_random_dir_gen',
        'dmpipe-random-dir-gen-sg = dmpipe.target_sim:main_random_dir_gen_batch',
        'dmpipe-analyze-roi-sg = dmpipe.target_analysis:main_roi_batch',
        'dmpipe-analyze-sed-sg = dmpipe.target_analysis:main_sed_batch',
        'dmpipe-simulate-roi = dmpipe.target_sim:main_roi_single',
        'dmpipe-simulate-roi-sg = dmpipe.target_sim:main_roi_batch',
        'dmpipe-convert-castro = dmpipe.dm_spectral:main_convert_single',
        'dmpipe-convert-castro-sg = dmpipe.dm_spectral:main_convert_batch',
        'dmpipe-stack-likelihood = dmpipe.dm_spectral:main_stack_likelihood_single',
        'dmpipe-stack-likelihood-sg = dmpipe.dm_spectral:main_stack_likelihood_batch',
        'dmpipe-collect-sed = dmpipe.dm_collect:main_collect_sed_single',
        'dmpipe-collect-sed-sg = dmpipe.dm_collect:main_collect_sed_batch',
        'dmpipe-collect-limits = dmpipe.dm_collect:main_collect_limits_single',
        'dmpipe-collect-limits-sg = dmpipe.dm_collect:main_collect_limits_batch',
        'dmpipe-collect-stacked-limits-sg = dmpipe.dm_collect:main_collect_stacked_limits_batch',
        'dmpipe-spec-table = dmpipe.dm_spectral:main_spec_table',
        'dmpipe-pipeline-dsph = dmpipe.pipeline_dsph:main_chain',
        'dmpipe-plot-dm-spectra = dmpipe.scripts.plot_dm_spectra:main_single', 
        'dmpipe-plot-dm = dmpipe.scripts.plot_castro_dm:main_single', 
        'dmpipe-plot-dm-sg = dmpipe.scripts.plot_castro_dm:main_batch', 
        'dmpipe-plot-stacked-dm-sg = dmpipe.scripts.plot_castro_dm:main_batch_stacked', 
        'dmpipe-plot-limits = dmpipe.scripts.plot_limits:main_single', 
        'dmpipe-plot-limits-sg = dmpipe.scripts.plot_limits:main_batch', 
        'dmpipe-plot-stacked-limits-sg = dmpipe.scripts.plot_limits:main_batch_stacked', 
        'dmpipe-plot-castro = dmpipe.scripts.plot_castro:main_single', 
        'dmpipe-plot-castro-sg = dmpipe.scripts.plot_castro:main_batch',
        'dmpipe-calc-sed-limits = dmpipe.scripts.calc_sed_limits:main', 
    ]},
    install_requires=[
        'numpy >= 1.6.1',
        'astropy >= 1.2.1',
        'matplotlib >= 1.5.0',
        'scipy >= 0.14',
        'fermipy >= 0.14.0',
        'pyyaml',
        'healpy',
        'dmsky'
    ],
    extras_require=dict(
        all=[],
    ),
)
