#!/usr/bin/env python
from setuptools import setup, find_packages
import versioneer

setup(
    name='dmpipe',
    version=versioneer.get_version(),
    cmdclass=versioneer.get_cmdclass(),
    author='Matthew Wood',
    author_email='mdwood@slac.stanford.edu',
    description='Pipeline Scripts for LAT DM Analysis',
    license='BSD',
    packages=find_packages(),
    include_package_data=True,
    url="https://github.com/fermiPy/dmpipe",
    classifiers=[
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Scientific/Engineering :: Astronomy',
        'Development Status :: 4 - Beta',
    ],
    scripts=[],
    entry_points={'console_scripts': [
        'dmpipe-analyze-roi = dmpipe.target_analysis:AnalyzeROI.main',
        'dmpipe-analyze-roi-sg = dmpipe.target_analysis:AnalyzeROI_SG.main',
        'dmpipe-analyze-sed = dmpipe.target_analysis:AnalyzeSED.main',
        'dmpipe-analyze-sed-sg = dmpipe.target_analysis:AnalyzeSED_SG.main',
        'dmpipe-prepare-targets = dmpipe.target_analysis:PrepareTargets.main',
        'dmpipe-random-dir-gen = dmpipe.target_sim:RandomDirGen.main',
        'dmpipe-random-dir-gen-sg = dmpipe.target_sim:RandomDirGen_SG.main',
        'dmpipe-simulate-roi = dmpipe.target_sim:SimulateROI.main',
        'dmpipe-simulate-roi-sg = dmpipe.target_sim:SimulateROI_SG.main',
        'dmpipe-convert-castro = dmpipe.dm_spectral:ConvertCastro.main',
        'dmpipe-convert-castro-sg = dmpipe.dm_spectral:ConvertCastro_SG.main',
        'dmpipe-stack-likelihood = dmpipe.dm_spectral:StackLikelihood.main',
        'dmpipe-stack-likelihood-sg = dmpipe.dm_spectral:StackLikelihood_SG.main',
        'dmpipe-collect-sed = dmpipe.dm_collect:CollectSED.main',
        'dmpipe-collect-sed-sg = dmpipe.dm_collect:CollectSED_SG.main',
        'dmpipe-collect-limits = dmpipe.dm_collect:CollectLimits.main',
        'dmpipe-collect-limits-sg = dmpipe.dm_collect:CollectLimits_SG.main',
        'dmpipe-collect-stacked-limits-sg = dmpipe.dm_collect:CollectStackedLimits_SG.main',
        'dmpipe-spec-table = dmpipe.dm_spectral:SpecTable.main',
        'dmpipe-pipeline-dsph = dmpipe.pipeline_dsph:main_chain',
        'dmpipe-plot-dm-spectra = dmpipe.dm_plotting:PlotDMSpectra.main', 
        'dmpipe-plot-dm = dmpipe.dm_plotting:PlotDM.main', 
        'dmpipe-plot-dm-sg = dmpipe.dm_plotting:PlotDM_SG.main', 
        'dmpipe-plot-stacked-dm-sg = dmpipe.dm_plotting:PlotStackedDM_SG.main', 
        'dmpipe-plot-limits = dmpipe.dm_plotting:PlotLimits.main', 
        'dmpipe-plot-limits-sg = dmpipe.dm_plotting:PlotLimits_SG.main', 
        'dmpipe-plot-stacked-limits-sg = dmpipe.dm_plotting:PlotStackedLimits_SG.main', 
        'dmpipe-plot-castro = dmpipe.dm_plotting:PlotCastro.main',
        'dmpipe-plot-castro-sg = dmpipe.dm_plotting:PlotCastro_SG.main',
        'dmpipe-calc-sed-limits = dmpipe.scripts.calc_sed_limits:main', 
    ]},
    install_requires=[
        'numpy >= 1.6.1',
        'astropy >= 1.2.1',
        'matplotlib >= 1.5.0',
        'scipy >= 0.14',
        'fermipy >= 0.14.0',
        'pyyaml',
        'healpy',
        'dmsky'
    ],
    extras_require=dict(
        all=[],
    ),
)
